Problem 1 (q.1)

In [ ]:
import numpy as np

arr_empty = np.empty((2, 2))
print(arr_empty)


[[3.85706348e-315 0.00000000e+000]
 [6.72720545e-310 5.77904633e-317]]


q2

In [ ]:
import numpy as np

arr_ones = np.ones((4, 2))
print(arr_ones)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

arr_full = np.full((3, 3), fill_value=7)
print(arr_full)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
import numpy as np

base = np.array([[5, 6, 7], [8, 9, 10]])
arr_zeros_like = np.zeros_like(base)
print(arr_zeros_like)


In [ ]:
import numpy as np

base = np.array([[5, 6, 7], [8, 9, 10]])
arr_ones_like = np.ones_like(base)
print(arr_ones_like)


In [ ]:
import numpy as np

new_list = [1, 2, 3, 4]
np_arr = np.array(new_list)
print(np_arr)


Problem 2

In [ ]:
import numpy as np

arr = np.arange(10, 50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

identity = np.eye(3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

arr = np.random.random(30)
print("Array:", arr)
print("Mean:", arr.mean())


Array: [8.55557436e-01 2.88848227e-01 3.05104288e-01 7.56590977e-01
 8.34377102e-01 4.55741016e-01 7.22349060e-01 2.62683634e-01
 6.22430177e-01 2.38421710e-01 8.03984714e-01 3.21748274e-01
 8.12882173e-01 2.61799372e-01 7.38814922e-01 1.59756846e-01
 5.74676703e-01 6.24549455e-01 7.92317666e-02 5.08417384e-02
 2.52428432e-01 5.05636591e-01 6.33119044e-04 5.42472574e-01
 8.23714275e-01 8.56912986e-01 9.09003089e-02 2.57569871e-01
 3.20589548e-01 3.83072696e-01]
Mean: 0.460143999788456


In [ ]:
import numpy as np

arr = np.random.random((10, 10))
print("Min:", arr.min())
print("Max:", arr.max())


Min: 0.019265603668355946
Max: 0.9968581098662991


In [ ]:
import numpy as np

arr = np.zeros(10)
arr[4] = 1
print(arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


In [ ]:
import numpy as np

arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np

board = np.zeros((8, 8), dtype=int)
board[1::2, ::2] = 1
board[::2, 1::2] = 1
print(board)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])


In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

add_result = x + y
print(add_result)


In [ ]:
import numpy as np

sub_result = x - y
print(sub_result)


In [ ]:
import numpy as np

mul_result = x * 3
print(mul_result)


In [ ]:
import numpy as np

square_result = x ** 2
print(square_result)


In [ ]:
import numpy as np

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("v·w =", dot_vw)
print("x·v =", dot_xv)
print("x·y =\n", dot_xy)


In [ ]:
import numpy as np


row_concat = np.concatenate((x, y), axis=0)
print("Row concat x & y:\n", row_concat)

col_concat = np.column_stack((v, w))
print("Column concat v & w:\n", col_concat)


In [ ]:
import numpy as np

try:
    bad_concat = np.concatenate((x, v), axis=0)
    print(bad_concat)
except Exception as e:
    print("Error:", e)


Error: name 'x' is not defined


Problem 4

In [ ]:
import numpy as np

A = np.array([[3,4],
              [7,8]])

B = np.array([[5,3],
              [2,1]])


In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])

A_inv = np.linalg.inv(A)
identity = A @ A_inv

print("A inverse:\n", A_inv)
print("A * A_inv:\n", identity)


In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

AB = A @ B
BA = B @ A

print("AB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal?:", np.array_equal(AB, BA))


In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

lhs = (A @ B).T
rhs = B.T @ A.T

print("(AB)^T =\n", lhs)
print("B^T A^T =\n", rhs)
print("Are they equal?:", np.array_equal(lhs, rhs))


(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Are they equal?: True
